/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'physi' at '7/25/16 11:09 PM' with Gradle 2.14
 *
 * @author physi, @date 7/25/16 11:09 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
